import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight } from "lucide-react";
import { SiteLayout } from "@/components/site-layout";
import { images, pageHead } from "@/lib/site";

export const Route = createFileRoute("/process")({ head: () => pageHead("Our Process", "Discover the approach behind Mahamba Kitchen Projects' custom kitchens, storage and living spaces.", images.neutral), component: Process });
const steps = [
  { no: "01", title: "The conversation", body: "Tell us about your space and the ideas you have for it. We begin by understanding what you need and what matters most to you." },
  { no: "02", title: "The direction", body: "We work through the layout, materials and details that will make the space both useful and unmistakably yours." },
  { no: "03", title: "The craftsmanship", body: "From cabinetry to finishing touches, the work comes together with care and attention to every line." },
  { no: "04", title: "The finishing touch", body: "The result is a space made for daily life—beautiful to look at and a pleasure to use." },
];
function Process() { return <SiteLayout><section className="site-container grid gap-12 pb-20 pt-16 md:grid-cols-2 md:items-end md:gap-20 md:pb-28 md:pt-24"><div><p className="eyebrow text-sage">The Mahamba approach</p><h1 className="display-title mt-6">Good spaces begin with <em className="text-gold">good listening.</em></h1><p className="body-copy mt-8 max-w-md">The best work starts with understanding your home, your taste and the way you want to live in it.</p></div><div className="image-frame aspect-[4/5] max-h-[630px]"><img src={images.neutral} alt="Finished kitchen with neutral cabinetry and island sink" /></div></section><section className="border-t border-border py-20 md:py-28"><div className="site-container grid gap-12 md:grid-cols-[.7fr_1.3fr] md:gap-24"><div><p className="eyebrow text-sage">How it comes together</p><h2 className="section-title mt-5">From idea to <em>everyday.</em></h2></div><div>{steps.map(step => <div key={step.no} className="grid grid-cols-[45px_1fr] gap-5 border-t border-border py-8"><span className="eyebrow pt-2 text-gold">{step.no}</span><div><h3 className="font-serif text-4xl">{step.title}</h3><p className="body-copy mt-3 max-w-lg">{step.body}</p></div></div>)}</div></div></section><section className="site-container py-20 text-center md:py-28"><p className="eyebrow text-sage">Let's begin</p><h2 className="section-title mx-auto mt-5 max-w-xl">Your idea is the <em>starting point.</em></h2><Link to="/contact" className="rule-link mt-8">Talk to us <ArrowUpRight size={16} /></Link></section></SiteLayout>; }