import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight } from "lucide-react";
import { SiteLayout } from "@/components/site-layout";
import { images, pageHead } from "@/lib/site";

export const Route = createFileRoute("/services")({ head: () => pageHead("Our Services", "Bespoke kitchens, wardrobes, TV units and custom woodworking for your home from Mahamba Kitchen Projects.", images.marble), component: Services });

const services = [
  { no: "01", title: "Bespoke kitchens", body: "From generous islands to considered cabinetry, kitchens designed around the way you cook, gather and live.", image: images.marble, alt: "White marble kitchen island and custom cabinetry" },
  { no: "02", title: "Wardrobes & storage", body: "Beautifully fitted storage that makes space for everything, with a finish that feels at home in yours.", image: images.glass, alt: "Custom glass-fronted cabinetry and storage" },
  { no: "03", title: "TV & living units", body: "Entertainment walls, shelving and built-in details that bring a room together without sacrificing function.", image: images.entertainment, alt: "Custom TV and entertainment wall with fluted paneling" },
];
function Services() { return <SiteLayout><section className="site-container grid gap-10 pb-20 pt-16 md:grid-cols-2 md:items-end md:gap-20 md:pb-28 md:pt-24"><div><p className="eyebrow text-sage">What we create</p><h1 className="display-title mt-6">Made to fit.<br /><em className="text-gold">Made to last.</em></h1><p className="body-copy mt-8 max-w-md">We create custom woodworking that works beautifully for real life—spaces with purpose, personality and a sense of place.</p></div><div className="image-frame aspect-[5/4]"><img src={images.graphite} alt="Custom graphite kitchen cabinetry and integrated appliances" /></div></section><section className="border-t border-border py-20 md:py-28"><div className="site-container"><p className="eyebrow text-sage">Our specialties</p><div className="mt-9 space-y-0">{services.map(s => <div key={s.no} className="grid gap-6 border-t border-border py-10 md:grid-cols-[65px_1fr_1fr_220px] md:items-center md:gap-10"><span className="eyebrow text-gold">{s.no}</span><h2 className="font-serif text-4xl md:text-5xl">{s.title}</h2><p className="body-copy max-w-sm">{s.body}</p><div className="image-frame aspect-[5/3] md:aspect-[4/3]"><img src={s.image} alt={s.alt} loading="lazy" /></div></div>)}</div></div></section><section className="bg-sage py-20 text-primary-foreground md:py-24"><div className="site-container flex flex-wrap items-end justify-between gap-8"><h2 className="section-title max-w-2xl">Every detail deserves <em>attention.</em></h2><Link to="/contact" className="rule-link text-primary-foreground">Discuss your project <ArrowUpRight size={16} /></Link></div></section></SiteLayout>; }